### ISSUE TITLE
Suppress printing of model characteristics

### ISSUE THREAD

**Issue by JanaTeepunkt** [PopovicMilica/causal_nets#3]
Hey there,

I repeat the estimation with causal nets around 100 times and it would be helpful to suppress the printing of the model characteristics and the loss, but I don't know how. I work in R and already tried "invisible()".

Thanks!

**Comment by PopovicMilica** [comment]
Hey Jana,

I extended the software slightly, so now the `causal_net_estimate` function includes an extra parameter called `verbose`. Its default value is set to True, but if you set it to False, it should suppress all printouts. You should only deinstall and install the causal_nets package again. If this works for you, please consider closing the issue. Thanks.

**Comment by JanaTeepunkt** [comment]
Thank you, it works fine :)
